# Generated by Django 6.0.5 on 2026-05-31 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="病人名稱")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("female", "女性"),
                            ("male", "男性"),
                            ("other", "其他 / 未揭露"),
                        ],
                        max_length=12,
                        verbose_name="性別",
                    ),
                ),
                (
                    "hospital_serial",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="醫院端流水號"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "病人",
                "verbose_name_plural": "病人",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SNPRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_serial",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="伺服器統一流水號"
                    ),
                ),
                (
                    "machine_serial",
                    models.CharField(max_length=40, verbose_name="機台流水號"),
                ),
                (
                    "data_file",
                    models.FileField(
                        upload_to="snp_data/%Y/%m/%d/", verbose_name="SNP 原始資料"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="接收時間"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "可產生報告"),
                            ("used", "已產生報告"),
                            ("error", "資料異常"),
                        ],
                        default="ready",
                        max_length=12,
                        verbose_name="狀態",
                    ),
                ),
            ],
            options={
                "verbose_name": "SNP 資料",
                "verbose_name_plural": "SNP 資料",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_serial",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="報告編號"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="reports/pdf/%Y/%m/%d/", verbose_name="PDF 報告檔"
                    ),
                ),
                (
                    "risk_summary",
                    models.JSONField(default=list, verbose_name="風險摘要"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="產生時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立者",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.patient",
                        verbose_name="病人",
                    ),
                ),
                (
                    "snp_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.snprecord",
                        verbose_name="SNP 資料",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康風險報告",
                "verbose_name_plural": "健康風險報告",
                "ordering": ["-created_at"],
            },
        ),
    ]
