# Generated by Django 6.0.5 on 2026-05-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snprecord",
            name="server_serial",
            field=models.CharField(
                editable=False,
                max_length=40,
                unique=True,
                verbose_name="伺服器統一流水號",
            ),
        ),
    ]
