# Generated by Django 6.0.5 on 2026-05-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_snprecord_server_serial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snprecord",
            name="nc_check_passed",
            field=models.BooleanField(default=False, verbose_name="NC check"),
        ),
        migrations.AddField(
            model_name="snprecord",
            name="pc_check_passed",
            field=models.BooleanField(default=False, verbose_name="PC check"),
        ),
        migrations.AddField(
            model_name="snprecord",
            name="snp_count",
            field=models.PositiveIntegerField(default=0, verbose_name="SNP 筆數"),
        ),
        migrations.AlterField(
            model_name="snprecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("ready", "待處理"),
                    ("used", "已建立報告"),
                    ("error", "資料異常"),
                ],
                default="ready",
                max_length=12,
                verbose_name="狀態",
            ),
        ),
    ]
