# Generated by Django 6.0.5 on 2026-05-31 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0003_snprecord_nc_check_passed_snprecord_pc_check_passed_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_risk_score",
                    models.PositiveIntegerField(default=0, verbose_name="總風險分數"),
                ),
                (
                    "risk_results",
                    models.JSONField(default=list, verbose_name="風險計算結果"),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="計算時間"),
                ),
                (
                    "snp_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessment",
                        to="reports.snprecord",
                        verbose_name="SNP 資料",
                    ),
                ),
            ],
            options={
                "verbose_name": "SNP 風險計算結果",
                "verbose_name_plural": "SNP 風險計算結果",
                "ordering": ["-calculated_at"],
            },
        ),
    ]
