# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_riskassessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="medical_advice",
            field=models.JSONField(default=list, verbose_name="固定醫療建議"),
        ),
        migrations.AddField(
            model_name="report",
            name="disclaimer",
            field=models.TextField(blank=True, verbose_name="免責聲明"),
        ),
    ]
