# Generated by Django 6.0.5 on 2026-06-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_patient_snprecord_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snprecord',
            name='server_serial',
            field=models.CharField(editable=False, max_length=40, unique=True, verbose_name='樣本流水號'),
        ),
    ]
