# Generated by Django 6.0.5 on 2026-06-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_snprecord_server_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snprecord',
            name='machine_serial',
            field=models.CharField(max_length=40, verbose_name='儀器編碼'),
        ),
    ]
